workflow WIP

diff --git a/.github/workflows/custom-release.yml b/.github/workflows/custom-release.yml
--- a/.github/workflows/custom-release.yml
+++ b/.github/workflows/custom-release.yml
@@ -151,11 +151,13 @@ jobs:
         working-directory: hvym-collective
         run: |
           cargo build --target wasm32-unknown-unknown --release
-          stellar contract optimize --wasm target/wasm32-unknown-unknown/release/hvym_collective.wasm || { echo "Optimization failed"; exit 1; }
+          ls -l target/wasm32-unknown-unknown/release/
+          stellar contract optimize --wasm-opt-opts "--enable-bulk-memory" --wasm target/wasm32-unknown-unknown/release/hvym_collective.wasm --wasm-out target/wasm32-unknown-unknown/release/hvym_collective.optimized.wasm || { echo "Optimization failed"; exit 1; }
           echo "Checking env-meta for hvym_collective.wasm"
-          stellar contract env-meta --wasm target/wasm32-unknown-unknown/release/hvym_collective.wasm > env-meta-output.txt 2>&1 || echo "Warning: env-meta failed for hvym_collective.wasm, continuing anyway"
+          stellar contract env-meta --wasm target/wasm32-unknown-unknown/release/hvym_collective.optimized.wasm > env-meta-output.txt 2>&1 || echo "Warning: env-meta failed for hvym_collective.wasm, continuing anyway"
           cat env-meta-output.txt >> debug_output.json
           cat env-meta-output.txt
+          ls -l target/wasm32-unknown-unknown/release/
       
       - name: Get package metadata
         working-directory: hvym-collective
@@ -299,30 +301,4 @@ jobs:
       release_description: 'Opus Token contract release'
       home_domain: 'pintheon.contracts'
       relative_path: opus_token
-      package: 'opus-token'
-    secrets:
-      release_token: ${{ secrets.GITHUB_TOKEN }}
-
-  release-pintheon-node-token:
-    needs: build-dependencies
-    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
-    with:
-      release_name: ${{ github.ref_name }}-pintheon-node-token
-      release_description: 'Pintheon Node Token contract release'
-      home_domain: 'pintheon.contracts'
-      relative_path: pintheon-node-deployer/pintheon-node-token
-      package: 'pintheon-node-token'
-    secrets:
-      release_token: ${{ secrets.GITHUB_TOKEN }}
-
-  release-pintheon-ipfs-token:
-    needs: build-dependencies
-    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
-    with:
-      release_name: ${{ github.ref_name }}-pintheon-ipfs-token
-      release_description: 'Pintheon IPFS Token contract release'
-      home_domain: 'pintheon.contracts'
-      relative_path: pintheon-ipfs-deployer/pintheon-ipfs-token
-      package: 'pintheon-ipfs-token'
-    secrets:
-      release_token: ${{ secrets.GITHUB_TOKEN }}
+      package: 'opus-token
